### ISSUE TITLE
Window cannot be shrunk narrower than some value

### ISSUE THREAD

**Issue by eternal-sorrow** [transmission-remote-gtk/transmission-remote-gtk#79] opened 2019-01-22 20:32 UTC
This causes me much inconvinience. I use tiling window manager and when the transmission window is vertically tiled, part of it is just hidden under the screen border

**Comment by LaserEyess** [comment] 2019-02-10 22:40
@eternal-sorrow I can't reproduce this on i3, what window manager are you using and what version of TRG? Can you send a couple of screenshots?

**Comment by eternal-sorrow** [comment] 2019-02-10 22:51
I'm using sway, the wayland clone of i3. Here's screenshot. You can see that part of TRG window is actually under the terminal window, which should not be because it's tiling. If TRG window would be tiled right, part of it just would just hide under the screen border.
![2019-11-02-h4524](https://user-images.githubusercontent.com/4847726/52540808-aabe2880-2d85-11e9-907b-eafb4c6c3a50.png)

**Comment by eternal-sorrow** [comment] 2019-02-10 22:57
Te problem is: even if I make the window floating (like on traditional, non-tiling environments), I can't manage to shrink it less than some value. When I try to do that, it expands back to that minimal value.

**Comment by eternal-sorrow** [comment] 2019-02-10 22:58
Version of TRG is 1.3.1

**Comment by LaserEyess** [comment] 2019-02-10 23:11
Can you try to get the same thing to happen in 1.4.1? Unfortunately I'm still not seeing this issue, so it may be something with XWayland or sway itself. This machine has an nvidia GPU so I can't currently test sway, but I have another machine I can try tomorrow.

**Comment by eternal-sorrow** [comment] 2019-02-10 23:14
TRG is not running on XWayland, it's running as native wayland application.

**Comment by LaserEyess** [comment] 2019-02-10 23:16
Ah right this is GTK, duh.

**Comment by eternal-sorrow** [comment] 2019-02-10 23:18
>Can you try to get the same thing to happen in 1.4.1?
At first I need to create a ebuild for 1.4.1. Gentoo does not have ebuilds for versions beyond 1.3.1.

**Comment by LaserEyess** [comment] 2019-02-10 23:21
Can't you just compile from source? You probably have all the makedepends if you're running Gentoo.

**Comment by eternal-sorrow** [comment] 2019-02-10 23:32
I've just built 1.4.1 and issue persists.

**Comment by LaserEyess** [comment] 2019-02-10 23:40
I'm sorry, I just installed sway on my laptop and it changes window sizes just fine. I seem to be having a lot of other issues with TRG on wayland though, so I'm not quite sure what's happening. Unfortunately I don't have the skills to debug this.

**Comment by eternal-sorrow** [comment] 2019-03-18 11:28
So? Any update? Is anyone able to shrink TRG window less than ~700 pixels?

**Comment by LaserEyess** [comment] 2019-03-19 21:08
@eternal-sorrow I am, on sway. I tried to take a picture but realized all my screenshotting tools were x11 only. TRG works well on wayland but my fonts and scaling looked really messed up so some stuff was a bit messed up. Regardless, I cannot reproduce your issue and I have no real GTK (or wayland) skills to speak of so I can't help in debugging.

**Comment by eternal-sorrow** [comment] 2019-03-20 00:54
@LaserEyess, Do you run TRG as a native sway application or with Xwayland?

**Comment by LaserEyess** [comment] 2019-03-20 23:37
I assume as a native wayland application? I don't believe I have Xwayland installed.

**Comment by eternal-sorrow** [comment] 2019-03-21 00:23
> I don't believe I have Xwayland installed.
You should have. It comes along with Xorg.

**Comment by LaserEyess** [comment] 2019-03-21 22:06
With `GDK_BACKEND=wayland` I was able to reproduce this.

**Comment by LaserEyess** [comment] 2019-03-21 22:40
I noticed something interesting when testing this. When disconnected from any server, I don't really get this issue. It's only when I'm connected. Furthermore, the only elements that DON'T seem to be adjusting to resizing is the text in the status bar on the bottom. They just shrink the empty space around the strings, and then at a certain point stop shrinking and coincidentally that's when I get the bug you have. So that might be the issue. It also fits with me not seeing this while the server is disconnected, since the only text at the bottom is "Disconnected".

**Comment by eternal-sorrow** [comment] 2019-06-05 15:39
So? Is there any way to fix this?

**Comment by eternal-sorrow** [comment] 2019-06-07 23:22
For now I patched my local version with small patch to reduce the width of connection status widget, by redusing the number of symbols in it, so that window now fits in  half of my screen. That'll do for me now, but I don't think that's a good approach in general.

**Comment by LaserEyess** [comment] 2019-06-12 21:32
I have no idea how to fix this, sorry. I know almost nothing about GTK or wayland programming. You would want @TingPing or even @ajf8 since they've done the most substantial work on GTK code.

**Comment by nickurbanik** [comment] 2021-07-22 07:43
@eternal-sorrow, where is that patch?  I don't have enough screen to show the whole width.  Perhaps I need to modify the patch to reduce this number of symbols further.

**Comment by eternal-sorrow** [comment] 2021-07-22 09:09
@nickurbanik 
```diff
diff --git a/src/trg-status-bar.c b/src/trg-status-bar.c
index 862e3f9..4c8cfb2 100644
--- a/src/trg-status-bar.c
+++ b/src/trg-status-bar.c
@@ -119,10 +119,10 @@ static void trg_status_bar_init(TrgStatusBar * self)
     gtk_box_pack_end(GTK_BOX(self), priv->turtleEventBox, FALSE, TRUE, 5);

     priv->speed_lbl = gtk_label_new(NULL);
-    gtk_box_pack_end(GTK_BOX(self), priv->speed_lbl, FALSE, TRUE, 10);
+    gtk_box_pack_end(GTK_BOX(self), priv->speed_lbl, FALSE, TRUE, 5);

     priv->free_lbl = gtk_label_new(NULL);
-    gtk_box_pack_end(GTK_BOX(self), priv->free_lbl, FALSE, TRUE, 30);
+    gtk_box_pack_end(GTK_BOX(self), priv->free_lbl, FALSE, TRUE, 5);
 }

 void
@@ -142,7 +142,7 @@ trg_status_bar_set_connected_label(TrgStatusBar * sb, JsonObject * session,
                                               TRG_PREFS_KEY_PROFILE_NAME,
                                               TRG_PREFS_CONNECTION);
     gchar *statusMsg =
-        g_strdup_printf(_("Connected: %s :: Transmission %s"),
+        g_strdup_printf(_("Conn: %s : v%s"),
                         profileName,
                         session_get_version_string(session));

```
Also rename your profile into something short, possibly one symbol.

**Comment by LaserEyess** [comment] 2022-01-15 14:46
I see three ways to fix this:

1. Put @eternal-sorrow's patch in, this fixes absolutely nothing but it makes the immediate issue go away
2. Pray that some of the refactoring I'm doing makes this go away. I have to refactor the status bar eventually since some of the methods it uses are deprecated or don't exist in gtk4.
3. Connect resize events to some sort of callback that allows us to check if the status bar is too long (how???) and then adjusts the text so that it never overruns the current pixel limit (which is???). 

I have no idea if 3 is possible with gtk APIs.

**Comment by LaserEyess** [comment] 2022-01-15 19:34
@ilf what is your environment?

**Comment by ilf** [comment] 2022-01-17 18:48
> @ilf what is your desktop environment/window manager?

dwm: https://dwm.suckless.org/

**Comment by LaserEyess** [comment] 2022-01-17 19:53
Ok, that's probably a deliberate choice by suckless devs then, because your WM should be able to shrink less than that. However, this could be done better on trg's side, the status bar resizing is pretty wonky. It should be possible to fix, I've been trying to google how

For my future reference: https://stackoverflow.com/a/32308945

**Comment by ilf** [comment] 2022-01-18 20:28
@LaserEyess: I doubt this is an issue with dwm.

First, suckless by [philosophy](https://suckless.org/philosophy/) keeps things simple. It doesn't have much code about size and resize, and it won't ever include work-arounds for specific ("pretty wonky") edge-cases, as those should be fixed in the original software producing these edge-cases.

But more importantly, this not only happens when [dwm](https://dwm.suckless.org/) actively manages my TRG window, but also when it doesn't manage TRG at all ("floating" mode) and I manually try to resize it, see https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/79#issuecomment-905790166
I expect this behaviour to be reproducible in other window managers and environments.

Thanks for working on this!

**Comment by LaserEyess** [comment] 2022-01-18 22:16
Yes I know what suckless is, or in this case what is isn't. I said it was a *deliberate choice* of suckless, not a bug. The bug is definitely in trg, and I will work on it. It annoys me as well, though the specific problem in the OP is now fixed.

**Comment by LaserEyess** [comment] 2022-01-19 02:08
@ilf please test #160 and see if that works for you.

**Closed** 2022-01-19 22:24 UTC

**Comment by ilf** [comment] 2022-01-20 18:02
@LaserEyess: Thanks for the patch. I will test it, but I probably won't have the ressources to do that in January. I will do it as soon as I can.

Meanwhile, maybe the original reporter @eternal-sorrow and the other subscriber @nickurbanik can also help test this?

Thanks.

**Comment by eternal-sorrow** [comment] 2022-01-20 18:03
I don't use TRG anymore, the web interface is sufficient for me.

**Comment by ilf** [comment] 2022-02-01 08:52
@LaserEyess: I tested https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/160 and it works. Now I can resize the window down to 267 Pixels. Thanks!

But it still has another weird behaviour that I assumed to be related to this, but apparently it isn't. The width of the torrent pane is as wide as the longest name of a torrent. This frequently leads to the torrent pane being wider than the window and getting a scrollbar. That in turn makes the progress bar irritating, since it's not immediately clear to the user what the relation of visible progress bar (say 50 %) actually has to the general progress (100 %).

What do you think about capping torrent pane width with the window width and shortening non-displayable torrent name text with ellipsis?

**Comment by LaserEyess** [comment] 2022-02-01 12:38
I think you're experiencing #22 (also #148). Column widths shouldn't be resized dynamically like they are. Not sure how to fix it right now.
