### ISSUE TITLE
Odd progress-bar colour choice with Ubuntu dark theme

### ISSUE THREAD

**Issue by flying-sausages** [transmission-remote-gtk/transmission-remote-gtk#102] opened 2020-06-05 14:28 UTC
The progress bar of a selected torrent looks a bit odd on dark themes. It is not possible to really tell the progress of a torrent when it is selected, and the first impression a selected torrent gives off is that it is at 0%, as the colour that is used in the normal torrent item is different for the "complete" section, but the "remaining" is practically the same in this theme.
![image](https://user-images.githubusercontent.com/23618693/83887987-1b3e4500-a741-11ea-8353-f49675287c69.png)

Possibly, the same colours should be used for the progress bar regardless of the item being selected? I'm curious what that would look like on other themes. I am curious if per-theme exceptions would be possible.

**Comment by LaserEyess** [comment] 2022-04-09 13:09
Could you check if this is fixed in the newest release? I'm guessing this is Ubuntu's issue since they're setting the color scheme, but there have been some updates to the GTK3 code to remove deprecations so this might be fixed.

**Comment by LaserEyess** [comment] 2022-06-16 14:41
I'm going to close this since too much has changed since this bug report was submitted. If it can be reproduced on the latest version please open a new bug.

**Closed by LaserEyess** 2022-06-16 14:41 UTC
