### ISSUE TITLE
Compilation on src/util.c breaks on macos Ventura 13.0.1 

### ISSUE THREAD

**Issue by sardanap** [transmission-remote-gtk/transmission-remote-gtk#208] opened 2022-12-07 21:28 UTC
I get this error:

```
FAILED: src/transmission-remote-gtk.p/util.c.o 
cc -Isrc/transmission-remote-gtk.p -Isrc -I../src -I/usr/local/Cellar/gtk+3/3.24.34/include/gtk-3.0 -I/usr/local/Cellar/glib/2.74.3/include/gio-unix-2.0 -I/usr/local/Cellar/cairo/1.16.0_5/include/cairo -I/usr/local/Cellar/libepoxy/1.5.10/include -I/usr/local/Cellar/pango/1.50.12/include/pango-1.0 -I/usr/local/Cellar/harfbuzz/5.3.1/include/harfbuzz -I/usr/local/Cellar/fribidi/1.0.12/include/fribidi -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/atk/2.38.0/include/atk-1.0 -I/usr/local/Cellar/pixman/0.40.0/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.14.1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libxcb/1.15/include -I/usr/local/Cellar/libxrender/0.9.10/include -I/usr/local/Cellar/libxext/1.3.5/include -I/usr/local/Cellar/libx11/1.8.2/include -I/usr/local/Cellar/libxau/1.0.10/include -I/usr/local/Cellar/libxdmcp/1.1.3/include -I/usr/local/Cellar/gdk-pixbuf/2.42.10/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -I/usr/local/Cellar/jpeg-turbo/2.1.4/include -I/usr/local/Cellar/libtiff/4.4.0_1/include -I/usr/local/Cellar/glib/2.74.3/include -I/usr/local/Cellar/glib/2.74.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.74.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre2/10.40/include -I/usr/local/Cellar/xorgproto/2022.2/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/ffi -I/usr/local/Cellar/json-glib/1.6.6/include/json-glib-1.0 -I/usr/local/Cellar/icu4c/71.1/include -I/usr/local/Cellar/libsoup/3.2.2/include/libsoup-3.0 -I/usr/local/Cellar/libpsl/0.21.1_5/include -I/usr/local/Cellar/libnghttp2/1.51.0/include -I/usr/local/Cellar/geoip/1.6.12/include/ -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -std=gnu99 -O2 -g -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_70 -funsigned-char -fstack-protector-strong -Winline -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Werror=format=2 -Werror=implicit-function-declaration -Werror=pointer-arith -Werror=init-self -Werror=missing-include-dirs -Werror=date-time -Wdeprecated-declarations -Wdeprecated -fPIE -MD -MQ src/transmission-remote-gtk.p/util.c.o -MF src/transmission-remote-gtk.p/util.c.o.d -o src/transmission-remote-gtk.p/util.c.o -c ../src/util.c
../src/util.c:332:9: error: expected expression
        const gchar *resultStr = json_object_get_string_member(response, "result");
        ^
../src/util.c:333:25: error: use of undeclared identifier 'resultStr'
        return g_strdup(resultStr ? resultStr : "Server responded, but with no result.");
                        ^
../src/util.c:333:37: error: use of undeclared identifier 'resultStr'
        return g_strdup(resultStr ? resultStr : "Server responded, but with no result.");
                                    ^
3 errors generated.
ninja: build stopped: subcommand failed.

this is the offending code:

case FAIL_RESULT_UNSUCCESSFUL: 
        const gchar *resultStr = json_object_get_string_member(response, "result");
        return g_strdup(resultStr ? resultStr : "Server responded, but with no result.");

putting braces to it fixed the problem for me

case FAIL_RESULT_UNSUCCESSFUL: {
        const gchar *resultStr = json_object_get_string_member(response, "result");
        return g_strdup(resultStr ? resultStr : "Server responded, but with no result.");
     }
```

**Comment by LaserEyess** [comment] 2022-12-07 22:35
@sardanap do you have build instructions? I could add macOS to the CI. I'm surprised gcc doesn't give a warning for this, though. Quite clearly wrong, although in practice it doesn't do anything bad.

**Comment by TingPing** [comment] 2022-12-07 22:47
@LaserEyess It is part of `pedantic`:

```
../src/util.c: In function ‘make_error_message’:
../src/util.c:332:9: warning: a label can only be part of a statement and a declaration is not a statement [-Wpedantic]
  332 |         const gchar *resultStr = json_object_get_string_member(response, "result");
      |         ^~~~~
```

**Comment by sardanap** [comment] 2022-12-08 09:47
@LaserEyess i don't have detailed instructions.

I've used  https://brew.sh/  to install meson and all the needed libraries.

I've been using brew for quite a long time so i cannot tell you the exact packages/libraries needed

Basically i kept installing libraries with brew until meson stopped complaining.

so:
meson setup --prefix="/usr/local/" build (brewing in libraries until meson ended complain)
meson compile -C build
i dont  do the meson install part because i just run the executable build/src/transmission-remote-gtk

on and btw macos uses clang so maybe this explains the oddity 
cc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)

Hope this helps

**Comment by LaserEyess** [comment] 2022-12-08 16:29
where does 71.1 come from? Is there a way to query this path with `brew $something icu4c` ?

**Comment by sardanap** [comment] 2022-12-08 16:41
the error was:
Package icu-uc was not found in the pkg-config search path.
Perhaps you should add the directory containing `icu-uc.pc'
to the PKG_CONFIG_PATH environment variable

so i did the old way:

find -L . -name icu-uc.pc

Anyway i'll file a bug on homebrew and get back to you asap

**Comment by LaserEyess** [comment] 2022-12-08 16:46
I understand the error, the issue is I can only test this by force pushing and waiting for the CI to fail. If I had actual hardware to test this on it would be a different story, but I don't and I'm not willing to set up a macOS VM for this. As I said in the PR, I'm not against this but it's beyond my ability to solve. If it gets fixed in homebrew upstream then it can be revisited.

**Comment by TingPing** [comment] 2022-12-08 20:39
Nothing is broken, its just how brew works.

Unlike a Linux system, brew has to integrate into macOS without causing conflicts. As such some libraries are kinda-sorta-private.

I don't have a mac atm to give a step by step, but generally if you use a brew Formula everything will work. And you can use `brew install --interactive $your_formula` to open a shell where the environment is set up for you.

**Comment by TingPing** [comment] 2022-12-08 20:41
There is a chance next year I'll get a macbook for work and then I can spend a minute on the CI.

**Comment by sardanap** [comment] 2022-12-09 07:39
@TingPing you are right.
I've opened a ticket and this is the answer:

------------------------------------------------
This is expected behaviour, because icu4c is keg-only. From brew info icu4c:

icu4c is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

If you need to have icu4c first in your PATH, run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.zshrc

For compilers to find icu4c you may need to set:
  export LDFLAGS="-L/usr/local/opt/icu4c/lib"
  export CPPFLAGS="-I/usr/local/opt/icu4c/include"

For pkg-config to find icu4c you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
--------------------------------------------------------------

So all you need to do is to set
export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
before the meson setup

**Closed** 2022-12-10 16:27 UTC
